#!/bin/sh
PATH=$PATH:.:##PREFIX##/lib/sh
. gpushd.sh

sock=$(get_sock) || exit 1
check_sock $sock || exit 1

temp=$(tempfile)
if [ -z "$1" ]
then
  gpushd-client --pop $sock > $temp
else
  gpushd-client --pop="$1" $sock > $temp
fi
less $temp
rm $temp
