#!/bin/sh
PATH=$PATH:.:/usr/local/lib/gpushd
. gpushd.sh

sock=$(get_sock) || exit 1
check_sock $sock || exit 1

temp=$(tempfile)
if [ -z "$1" ]
  gpushd-client --pop $sock > $temp
else
  gpushd-client --pop="$1" $sock > $temp
fi
less $temp
rm $temp
